# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Github தமிழா
email: rbrajbharath1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning anything that interests me. Want to be specialised in observing the nature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.githubtamizha.com" # the base hostname & protocol for your site
twitter_username: rbrajbharath1
github_username:  rajbharath

# Build settings
markdown: kramdown
